
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 08 12:25:14 CET 2018
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TESIS = 27;
  public static final int REAL2INT = 15;
  public static final int TIPO = 34;
  public static final int POR = 25;
  public static final int PI = 32;
  public static final int VARS = 16;
  public static final int CLOG = 35;
  public static final int CENT = 33;
  public static final int PC = 19;
  public static final int INT2REAL = 14;
  public static final int NOT = 9;
  public static final int AND = 10;
  public static final int IGUALQUE = 28;
  public static final int MAYORQUE = 22;
  public static final int CREAL = 36;
  public static final int OR = 11;
  public static final int PLOT = 7;
  public static final int DIV = 24;
  public static final int IF = 2;
  public static final int UMENOS = 31;
  public static final int ASOP = 20;
  public static final int EOF = 0;
  public static final int SIZE = 12;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int MENOS = 30;
  public static final int IDENT = 37;
  public static final int COLOR = 38;
  public static final int MENORQUE = 21;
  public static final int ELSE = 4;
  public static final int COSENO = 18;
  public static final int WHILE = 6;
  public static final int SENO = 17;
  public static final int THEN = 3;
  public static final int PROG = 13;
  public static final int END = 5;
  public static final int PAREN = 26;
  public static final int DO = 8;
  public static final int MAS = 23;
}

